

const Datalist = [
    {
        id : 1,
        username : 'pawan',
        BookName : 'python Mastery',
        smalldec : 'get master in python notes and video',
        decricption : 'decricption',
        videosrc : 'https://www.youtube.com/embed/UrsmFxEIp5k?si=jryOxHnYlUYwnzDH',
        image : 'data/python.jpg',
        notessrc : '',

    },
    {
        id : 2,
        username : 'pawan',
        BookName : 'java',
        smalldec : 'master in java by pawan',
        decricption : 'decricption',
        videosrc : 'https://www.youtube.com/embed/239ubH043lI?si=RSVcCqob3IU8Vjl6',
        image : 'data/java.png',
        notessrc : '',
    },
    {
        id : 3,
        username : 'pawan',
        BookName : 'c',
        smalldec : 'want to lern c',
        decricption : 'decricption lorem343 dnlsnfdn msndfknsdnfjkskf sjkdfndmkfnkjsdnf sdkjfn sdf kjsndkfnksnkf ojsdnf dmfnks f kskdf nsbg nsdfns gsg kjsn fsgjndks gkfng vnsjgn dfnjsv nkjsg  snf s kfsd fns fkjnsdf nsdkjv snd vnsdv nsd vjlsndv ndjnv dbdsm vnsdmv nvsdk jv',
        videosrc : 'https://www.youtube.com/embed/irqbmMNs2Bo?si=XZcal1tom8cNa1OI',
        image : 'data/c.png',
        notessrc : '',
    },
    {
        id : 4,
        username : 'pawan',
        BookName : 'C++ language',
        smalldec : 'get master in c++ notes and video',
        decricption : 'decricption',
        videosrc : 'https://www.youtube.com/embed/e7sAf4SbS_g?si=551SJduUdxoy6JAB',
        image : 'data/C++.webp',
        notessrc : '',
    },
    {
        id : 5,
        username : 'pawan',
        BookName : 'CSS Mastery course',
        smalldec : 'Css handwritten notes',
        decricption : 'decricption',
        videosrc : 'https://www.youtube.com/embed/KRXsAGEYrwo?si=1msgj58sMqvlIH8d',
        image : 'data/CSS.png',
        notessrc : '',
    },
    {
        id : 6,
        username : 'pawan',
        BookName : 'HTML super notes',
        smalldec : 'html super notes and video',
        decricption : 'decricption',
        videosrc : 'https://www.youtube.com/embed/HcOc7P5BMi4?si=PrJiCHLL-ykvPf11',
        image : 'data/HTML.jpg',
        notessrc : '',
    },
    {
        id : 7,
        username : 'pawan',
        BookName : 'java scricpt',
        smalldec : 'handwritten Notes and video',
        decricption : 'decricption',
        videosrc : 'https://www.youtube.com/embed/VlPiVmYuoqw?si=OYIk5XUugIjAXYNE',
        image : 'data/Js.png',
        notessrc : '',
    },
    {
        id : 8,
        username : 'pawan',
        BookName : 'React full tutorial',
        smalldec : 'react handWritten notes and video',
        decricption : 'decricption',
        videosrc : 'https://www.youtube.com/embed/M9O5AjEFzKw?si=EU3ObdHEE_Z38d-9',
        image : 'data/react.webp',
        notessrc : '',
    },
    {
        id : 9,
        username : 'pawan',
        BookName : 'java',
        smalldec : 'master in java by pawan',
        decricption : 'decricption',
        videosrc : 'https://www.youtube.com/embed/239ubH043lI?si=RSVcCqob3IU8Vjl6',
        image : 'data/java.png',
        notessrc : '',
    },
]
export default Datalist